# aliases
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias back='cd $OLDPWD'
alias c='clear'
alias cd..='cd ..'
alias cp='cp -iv'
alias chmod="chmod -c"
alias chmod="chmod -c"
alias df='df -h -x squashfs -x tmpfs -x devtmpfs'
alias diff='colordiff'
alias egrep='egrep --colour=auto'
alias e="vim -O "
alias E="vim -o "
alias extip='curl icanhazip.com'
alias grep='grep --color=auto'
alias l.=' ls -lhFa --time-style=long-iso --color=auto'
alias ll=' ls'
alias ls=' ls -lhF --time-style=long-iso --color=auto'
alias lsmount='mount |column -t'
alias mkdir='mkdir -pv'
alias ports='netstat -tulanp'
alias h='history'
alias j='jobs -l'
alias mv='mv -iv'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'
alias svim='sudo vim'
alias tn=' tmux new -s'
alias vdestroy='vagrant destroy'
alias vssh='vagrant ssh'
alias vup='vagrant up'
alias watch='watch -d'
alias weather='curl wttr.in'
alias wget='wget -c'

##Scrcpy Shortcuts
alias scrcpy-='scrcpy --video-codec=h265 --max-size=1080 --max-fps=30 --no-audio --turn-screen-off --stay-awake --always-on-top'
alias scrcpy-d='scrcpy -d --video-codec=h265 --max-size=1080 --max-fps=30 --no-audio --turn-screen-off --stay-awake --always-on-top'
alias scrcpy-d1='scrcpy -d -s HT69A0204070 --video-codec=h265 --max-size=1080 --max-fps=30 --no-audio --turn-screen-off --stay-awake --always-on-top'
alias scrcpy-d3='scrcpy -d -s 92GAX00UA1 --video-codec=h265 --max-size=1080 --max-fps=30 --no-audio --turn-screen-off --stay-awake --always-on-top'
alias scrcpy-e='scrcpy --tcpip --video-codec=h265 --max-size=1080 --max-fps=30 --no-audio --turn-screen-off --stay-awake --always-on-top'
alias scrcpy-e1='scrcpy -s 192.168.0.191:5555 --tcpip --video-codec=h265 --max-size=1080 --max-fps=30 --no-audio --turn-screen-off --stay-awake --always-on-top'
alias scrcpy-e3='scrcpy -s 192.168.0.193:5555 --tcpip --video-codec=h265 --max-size=1080 --max-fps=30 --no-audio --turn-screen-off --stay-awake --always-on-top'
alias scrcpycam='scrcpy --video-source=camera --camera-size=1920x1080 -e'

##SSH Shortcuts
alias nixace='ssh temhr@192.168.0.200'
alias nixsun='ssh temhr@192.168.0.202'
alias nixtop='ssh temhr@192.168.0.203'
alias nixvat='ssh temhr@192.168.0.201'
alias nixzen='ssh temhr@192.168.0.204'

##NixOS Shortcuts
alias hmswitch='home-manager switch --flake /home/temhr/nixlab'
alias lboot='sudo nixos-rebuild boot --flake /home/temhr/nixlab && sudo reboot'
alias lfup='nix flake update --flake /home/temhr/nixlab'
alias lswitch='sudo nixos-rebuild switch --flake /home/temhr/nixlab'
alias ltest='sudo nixos-rebuild test --flake /home/temhr/nixlab'
alias rboot='sudo nixos-rebuild boot --flake github:temhr/nixlab && sudo reboot'
alias rfup='nix flake update --flake /home/temhr/nixlab && /run/wrappers/bin/sudo -u "temhr" GIT_SSH_COMMAND="ssh -i ~/.ssh/id_flake_update -o BatchMode=yes -o StrictHostKeyChecking=no" /run/current-system/sw/bin/git push'
alias rswitch='sudo nixos-rebuild switch --flake github:temhr/nixlab'
alias rtest='sudo nixos-rebuild test --flake github:temhr/nixlab'
alias nlist='nixos-rebuild list-generations'

##Nix-Shell
alias nscowsay='nix shell nixpkgs#cowsay'

##Git
alias greset='git reset --hard origin/main && git pull --rebase'

## Check video drivers in use
alias vdr='lspci -n -n -k | grep -A 2 -e VGA -e 3D'
## Check active GPU driver
alias gpudr='glxinfo | grep -e OpenGL.vendor -e OpenGL.renderer'
## List available and default GPU
alias gpu='switcherooctl list'

## get top process eating memory
alias mem5='ps auxf | sort -nr -k 4 | head -5'
alias mem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias cpu5='ps auxf | sort -nr -k 3 | head -5'
alias cpu10='ps auxf | sort -nr -k 3 | head -10'

## List largest directories (aka "ducks")
alias dir5='du -cksh * | sort -hr | head -n 5'
alias dir10='du -cksh * | sort -hr | head -n 10'

## Safetynets
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'

## confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

## Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

## reload bash config
alias reload="source ~/.bashrc"

# Manage packages easier
if [ -f /usr/bin/apt ]; then
  alias update='sudo apt update'
  alias upgrade='sudo apt update && sudo apt dist-upgrade && sudo apt autoremove && sudo apt clean'
  alias install='sudo apt install'
fi
