GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:lXoPOu4wuoPYMaYi,iv:MtyZdJ5iVdBc9HcsHcGn3UeBZ48f3z+LMIN7uYB8OyI=,tag:UrFm557RZ3+vLozJ475bIg==,type:str]
sops:
    age:
        - recipient: age1492d3ceqx25evj5a469lxakw3j0v96aycuj7gyu07yr3777kgssstes332
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaDlwa1ZGNzB0ekVxblZt
            SnQzSUdyTjYveUlRT1MzNGhOa0hqU3dYV3pJCjArN3I4bUg4UkpDZ2tobit1cjlt
            dDRvSVBsR2pCZ0ZCTHE5TXd6VlhVRjAKLS0tIHJ1UStDaXBtQkxoQ2psdmIyQXBr
            RDErcnZDeWszZ3RqMWh4aHhoQi94cmsK8D/SrG4fC7cF4q1PhzaDP76Z/SLhPSW9
            pj5HYEiKvJj7Djwb2gkqt+hnC04YXpbog3kZAUjabBMAX8lUobGC2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e6v58rl5epzkjyf4uk5y34qeu35h8xs38mhj500sak3eq6pplp0s88c6pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM2liZDdyVlRBSFc3QlNS
            S2pMYVprQ0Z4QTd4ZFl4eDMxNkhwdXBsYkVNCnZvOFY5elJhNFFyY0tBYS9jSlJP
            QU1RbHczVWtMZmhyb3ZYZy9wU2xJSHcKLS0tIDMrOTkrN0wxcXBETEYzbXMwR212
            MEJNSTdGUG9McTk0eGVMcStSbEQ2RjAKhHMJY997xsiE1hxUliYITGaXoi1mxZ8e
            mrSfiAvmdDdbIRXEyfxLu8I1zCtz4D7mLv2Iosmxc5h+VUT6RhNU0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uc06xlk6sw8z3nzc9sxugvcdmsnyrapwdamewmxz03hfqqcc8d3q29ydjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUVlTVkFnbFFUcU81LzI2
            bmpmRHZ3WkIySW5wamo3NXp4bzhGbjh0djFFCndqMTZNL2xjNUJOazVEc1hrUTNT
            NzhEaWc0Tmw2QStLMUI4dVdPWDlwd3cKLS0tIEdTUFdaS0NuVVZTUG5uWHBNejlp
            NTRjcHlid2haWUlNdlFGZmFXb3pGK28KPsIm7sMGpgT6YuEAtWr1LK210x0DCIKa
            Nyk3qgFvoAAqe0cQ6NvKicDsC7Lo5axz5P2RymNV2mIci2DV52X80A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c2x4u2et0trw8vvtchxvrw9z2fazmxeqe2keawkzjejtvp9x75msxg9tcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNnFoaHBWTTBnU1p0Z2k5
            T3NQcTlZS3JEV1JNSFdpODBSYzk0RnhHZDJrCnZVZ2ErcHE4eEJrejVzMzZYelZa
            UHREdzYwMk4xQmtYSnlFM1NnNkxZc3MKLS0tIFo5N2Jsc2krNjdsQTR2L3VqNmgv
            UWFaMGNLQ1VRa1d6a0dmKzRqaXQ2NkUKPIi8OIVrZXj/pfa/aaAQiTtDPiNoW208
            8NhWntPl+ZGyCcgZPcga0ItKK6zvTGSLCPnXsLcfvZWUD6ReSW4LPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jn8vgw2896pp52z3vxmdadczt267wsaca4ct6n597djuvrccc7qtdjkx0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYmZBYWlCQmlsSGNKRXFY
            SVU3M3ZpNVNHSzNRemNwdXZMZXVaZWk1TzJZCjBsYTA5STEyNm4vbVdkTVBmR2hP
            UkdQSXlxVVVxVHRpTnB1SFdEWmlHMTQKLS0tIC90ZHIzcGFxSkVjUHpLb3NlVlEw
            aTVyRTUrVTI1TGU3M1JRdmNsTENJUVkKL+EjxVhRe1uKiEpoRc0gNKUOoK36Edfx
            rCV7fAokZ7qhVzMe855FHf5elFwtb5aY6owOY1qISUSd/6O1te46ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mt0jjfq5wp2wx49aj8a9l5k2ejz8xlgnd5jp3e7ysze8jkwa8c9qj2w4ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWEdUM2ZyR09rYWI4ekts
            b09peElqbjhWMVJEQTc4RVh4NThScy9WT2xnCmV6RzdxS2g0b3V4NmN5aUV0Qjll
            RGh2cENFYVg2SmFVam9jd0FGbW43K2sKLS0tIFd3bldXelAzUEI0bS9Da1lUNVFN
            YmJYOE1Id3ZpMVFIVldnODZKbkJXU0kK+BPi3pjDuHJFk5yynlhM4gPl/x/K8Jxg
            bZkZVN0bRUyB5xJZjBz/UDhuteKPVL9Oq0qzLAVwxDvDyqjCHOiZyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T15:09:20Z"
    mac: ENC[AES256_GCM,data:UGNroaPxRoCetPsKSzFolOm3IwAaG1+3xEhxWUZg2BqMBvNDf/6vIytRLLQ6FQEi+Ia/jLd64O8UxkbtqwxOh0HyWEN08DlMxJtuRxf1WvM3UwbnJmjZaoUHrBEbSIHcgzDXlTfZiDzFTiJ9tvRCzvh03pSZ81RJqKgDwot3BWk=,iv:47ax65BwGhTdiIgcg3S654JJ2mkvGtJn0Ak7OqhoWcU=,tag:hdCAUgDqikOAsuDoQd5K2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
