GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:lXoPOu4wuoPYMaYi,iv:MtyZdJ5iVdBc9HcsHcGn3UeBZ48f3z+LMIN7uYB8OyI=,tag:UrFm557RZ3+vLozJ475bIg==,type:str]
sops:
    age:
        - recipient: age1492d3ceqx25evj5a469lxakw3j0v96aycuj7gyu07yr3777kgssstes332
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L3RuZWNlLzR4ZWJNM2l5
            dWNDZWVjZVlUai94bkFhYkZXRmtIdjkwbmhZClpvWGRodEEzZGtzTGlZKzZMbkd3
            NDVSTmlyUzh5SkMwKzV5NCtoWmRRaEkKLS0tIEgvdVRaRVpDT252ekM0OTdXVkpX
            Q21LRnNUNWV1aEZrVUhxMEJ3ait4V1kKtgRcv71PoiggdHFoYeGmuIu1ntbpEqIW
            tnRICBsqyF0UIZW8OV9a1OALsn+Bcp0o9shrhr8hGdVFiv/xrNuXgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uc06xlk6sw8z3nzc9sxugvcdmsnyrapwdamewmxz03hfqqcc8d3q29ydjr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc25Gc1dlRldVeXBib3Fk
            MEpzR2M1aVhBeWN1NlZSdTBaTzhodWxqcnpjCmxiOUhWd1B5UHBtcjE1dmxIczk2
            cEVlMFpPMnRHYU9LOVM1aVVvV091Y2MKLS0tIE5vS0g3TGo5RlB0ZmxNWXNVRWpS
            QU5wVFZBb3FOaDdQVjJSdk9xQjB6ZzQK/9SIKbuH8wvwvrF3sx+O52jd+swlvvz/
            GxvguHzyRVMY+9ABD1al2Qs/++VzPYSJIvSmTt0PrFX4q0/H5qWKWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c2x4u2et0trw8vvtchxvrw9z2fazmxeqe2keawkzjejtvp9x75msxg9tcj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RklRbDJIbGtZUHRRMDJY
            V281MHVDSUNSSHZzRWlndTZrTDl1N0REaGxnCitXakNOSVpwbnlTemFFSWNTRHN0
            Vk85eXdaS0JydGIyRG5iVWNFSzdBU00KLS0tICtMaDd6NEM4SDlwY2tCa2ZTRFdY
            VnNpMmJGdVdzeHI2NlMvSTlwMDlIM0UKTeKTYWrjqW/eDzJ0LqYRUDBK6ok2QYDn
            STcy6lnIwx+2WHBQeaDEojCsRaHmdWLhIlAa1AtpT8GrebbC/ioDEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jn8vgw2896pp52z3vxmdadczt267wsaca4ct6n597djuvrccc7qtdjkx0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWGZJNkxwTjR2SHFDY2hw
            c3Z2eFE3aVVsYVNDWnZMRTFrTnBVejZzRm1JCnordEExMXlQUy9oVWR0Z0U3SHRV
            Si9YZ21wMXJjSm5vNktZbU9CZW1CVWsKLS0tIHB3b0ZSdG1VNzR6Wjh6TGE1cVlz
            S24rU3lud202eUx6M0tNRmxQZmV5MkUKtxPkMqyGk7QaDNeKQoDtQR7VBVGbOdQN
            tjBr2dbF+xZvgz04v6J50T5M9RZxQbTvUmzbcCQhnTwZiVqaQu/zsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mt0jjfq5wp2wx49aj8a9l5k2ejz8xlgnd5jp3e7ysze8jkwa8c9qj2w4ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ0c3ZjhJYTVjVUF0MlI3
            SDVIRzl5WDVad05rM1JuandRZEdSNDhUbUM0ClA3dHF3TDVwcWxGRUdzNGcyVktH
            QTJyWlRpY1dGdCtyanhpWGN6eDBlR0EKLS0tIGNHL3FOdTYwVjNNTHVudGpob1k1
            eGhWQU9jTVdqc042NVBJelcrQ0JCZVUKGT6N2wsAzFSgQ+EWctVqRrTiQpPTPXVn
            AfHK/OLXjtWvUdxyOtYjGazSo8UQIC2lF/qsFyZu5bt2Vln21gQudg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T15:09:20Z"
    mac: ENC[AES256_GCM,data:UGNroaPxRoCetPsKSzFolOm3IwAaG1+3xEhxWUZg2BqMBvNDf/6vIytRLLQ6FQEi+Ia/jLd64O8UxkbtqwxOh0HyWEN08DlMxJtuRxf1WvM3UwbnJmjZaoUHrBEbSIHcgzDXlTfZiDzFTiJ9tvRCzvh03pSZ81RJqKgDwot3BWk=,iv:47ax65BwGhTdiIgcg3S654JJ2mkvGtJn0Ak7OqhoWcU=,tag:hdCAUgDqikOAsuDoQd5K2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
